#! /bin/bash

function exec_docker() {
    args="$@"
    docker run \
        --user "$(id -u):$(id -g)" \
        --mount "type=bind,source=/home/$(id -u -n),destination=/home/$(id -u -n)" \
        -w "/home/$(id -u -n)" \
        --net host \
        --rm \
        -it "$(id -u -n)/kas" /bin/bash -c ". $(pwd)/src/poky/oe-init-build-env && $args"
}


function setup() {

    docker build . -t "$(id -u -n)/kas" \
            --build-arg  "USER_NAME=$(id -u -n)" \
            --build-arg  "GROUP_NAME=$(id -g -n)" \
            --build-arg  "GROUP_ID=$(id -g)" \
            --build-arg  "USER_ID=$(id -u)"
}


function run() {

    docker run \
        --user "$(id -u):$(id -g)" \
        --mount "type=bind,source=/home/$(id -u -n),destination=/home/$(id -u -n)" \
        -w "/home/$(id -u -n)" \
        --net host \
        --rm \
        -it "$(id -u -n)/kas"
}



if [ -z "$(docker images -q "$(id -u -n)/kas" 2> /dev/null)" ]; then
    setup
else
    run
fi