#! /bin/bash

readonly curr_dir="$(dirname ${0})"
readonly local_yocto_home="${YOCTO_HOME:-$HOME/data/yocto}"

function exec_docker() {
    args="$@"
    docker run \
        --user "$(id -u):$(id -g)" \
        --mount "type=bind,source=${local_yocto_home},destination=${local_yocto_home},readonly=false" \
        --mount "type=bind,source=${HOME}/.ssh,destination=${HOME}/.ssh,readonly=true" \
        -w "${local_yocto_home}" \
        --net host \
        --rm \
        -it "$(id -u -n)/kas" /bin/bash -c ". $(pwd)/src/poky/oe-init-build-env && $args"
}


function setup() {

    docker build ${curr_dir} -t "$(id -u -n)/kas" \
            --build-arg  "USER_NAME=$(id -u -n)" \
            --build-arg  "GROUP_NAME=$(id -g -n)" \
            --build-arg  "GROUP_ID=$(id -g)" \
            --build-arg  "USER_ID=$(id -u)"
}


function run() {

    docker run \
        --user "$(id -u):$(id -g)" \
        --mount "type=bind,source=${local_yocto_home},destination=${local_yocto_home},readonly=false" \
        --mount "type=bind,source=${HOME}/.ssh,destination=${HOME}/.ssh,readonly=true" \
        -w "${local_yocto_home}" \
        --net host \
        --rm \
        -it "$(id -u -n)/kas"
}

if [ -z "$(docker images -q "$(id -u -n)/kas" 2> /dev/null)" ]; then
    setup
else
    run
fi